### PR TITLE
Ian

### PR DESCRIPTION
**Pull request by IanAngillis**
Database can be created using a local mssql database. Make sure you've installed the data storage and processing module for Visual Studio and just run "update-database -v" in the pack manager console.

Next step is to add authorization and authentication to acces the Chess service.

### CODE REVIEW

**Comment by IanAngillis** [comment]
Working on it

**Comment by JoachimVeulemans** [comment]
Looking into Docker error

**Comment by JoachimVeulemans** [comment]
image
@IanAngillis, any ideas why?

**Comment by IanAngillis** [comment]
No idea, as it does build correctly on Ubuntu. Looking into it once more

**Pull request closed without merging**
